name: Python CI

on:
  push:
    branches:
      - sosa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: |
          pytest
